version: 2
jobs:
  build-test:
    docker:
      - image: circleci/node:10
    working_directory: ~/tretenFE
    steps:
      - checkout
      - run:
          name: Install jest gloablly
          command: sudo npm install -g jest
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: build source code
          command: npm run build
      - save_cache:
          paths:
            - node_modules
            - .next
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test
  deploy-to-staging:
    docker:
      - image: circleci/node:10
    working_directory: ~/tretenFE
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Deploy to heroku
          environment:
            HEROKU_API_KEY: 194d0430-242a-49d0-bc7d-8f0da38841ae
            HEROKU_APP_NAME: treten-ng
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git staging:master -f

workflows:
  version: 2
  deploy-build:
    jobs:
      - build-test
      - deploy-to-staging:
          requires:
            - build-test
          filters:
            branches:
              only: staging
